name: auth_project
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase core package for initializing Firebase in Flutter
  firebase_core: ^3.8.0

  # Firebase Authentication package for phone authentication
  firebase_auth: ^5.3.3

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment this section to include assets in your project
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
